name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  version-check:
    name: Version Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch main for comparison
        run: git fetch origin main

      - name: Compare version with main
        run: |
          PR_VERSION=$(jq -r .version package.json)
          MAIN_VERSION=$(git show origin/main:package.json | jq -r .version)

          echo "PR version: $PR_VERSION"
          echo "Main version: $MAIN_VERSION"

          if [ "$PR_VERSION" = "$MAIN_VERSION" ]; then
            echo "❌ Version has NOT been bumped. Please update package.json."
            exit 1
          else
            echo "✅ Version has been bumped."
          fi

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: version-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test
